version: '3'

services:
  locust-script:
    container_name: "locust-script"
    entrypoint: ["./entrypoint.sh"]
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - 8089:8089