# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc_create_vacancy.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import vacancy_pb2 as vacancy__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x18rpc_create_vacancy.proto\x12\x02pb\x1a\rvacancy.proto"s\n\x14\x43reateVacancyRequest\x12\r\n\x05Title\x18\x01 \x01(\t\x12\x13\n\x0b\x44\x65scription\x18\x02 \x01(\t\x12&\n\x08\x44ivision\x18\x03 \x01(\x0e\x32\x14.pb.Vacancy.DIVISION\x12\x0f\n\x07\x43ountry\x18\x04 \x01(\tB\x14Z\x12\x63yrex/vacancies/pbb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "rpc_create_vacancy_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"Z\022cyrex/vacancies/pb"
    _CREATEVACANCYREQUEST._serialized_start = 47
    _CREATEVACANCYREQUEST._serialized_end = 162
# @@protoc_insertion_point(module_scope)
